export const ROUTES = {
  ADMIN: {
    DASHBOARD: '/',
    LOGIN: '/login',
    MANAGE_USERS: '/users',
    MANAGE_QUIZ_CATEGORIES: '/categories',
    MANAGE_SUBJECTS: '/subjects',
    MANAGE_TOPICS: '/topics',
    MANAGE_QUESTION_BANK: '/questions',
    UPLOAD_QUESTIONS: '/upload-questions',
    CONFIGURE_ENTRY_FEE: '/entry-fee',
    CONFIGURE_PRIZE_POOL: '/prize-pool',
    CREATE_CONTEST: '/create-contest',
    SCHEDULE_CONTEST: '/schedule-contest',
    MONITOR_LIVE: '/monitor-live',
    EXCELLENCE_LEAGUE: '/excellence-league',
    LEADERBOARD: '/leaderboard',
    VIEW_REPORTS: '/reports',
    TRANSACTIONS: '/transactions',
    DEPOSITS: '/deposits',
    WITHDRAWALS: '/withdrawals',
    MANAGE_FEATURES: '/features',
    MANAGE_HOW_IT_WORKS: '/how-it-works',
    MANAGE_FAQ: '/faq',
    NOTIFICATIONS: '/notifications',
    SETTINGS: '/settings',
    SUPPORT_CONTACT: '/support-contact',
    TERMS_CONDITIONS: '/terms',
    PRIVACY_POLICY: '/privacy',
    REFUND_POLICY: '/refund',
    PROFILE: '/profile',
  }
};
